.TH WEBDIFF 1
.SH NAME
webdiff \- web secretary utility
.SH DESCRIPTION
.PP
.B Webdiff 
is part of the websec package. It is used internally by websec.

.SH SEE ALSO
/usr/share/doc/websec/README.

.SH AUTHOR
This manual page was written by Joop Stakenborg <pa3aba@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
