.\" 
.TH "WEBSEC" "1" "1.4.0" "" ""
.SH "NAME"
websec \- web secretary

.SH "SYNOPSIS"
\fBwebsec\fR <$HOME/.websec/url.list>

.SH "DESCRIPTION"
\fBWebsec\fR is a web page monitoring software. 
It will send you a changed web page with the contents
highlighted. The debian version of websec has been
changed, so the web\-pages archive will be stored in
\fI$HOME/.websec\fR, this is also the directory where
you should keep your url.list.


When called without an argument, \fBwebsec\fR will try to
open \fI$HOME/.websec/url.list\fR, but you can also 
provide a filename as the first argument.


You can add a line like \fIAddSubject = [websec]\fR to
url.list, websec will add \fI[websec]\fR to every subject
as a first word when mail is sent. You can then easily detect
this line by a mail filter.


The keywords \fIRetry\fR, \fIRetrywait\fR, and
\fITimeout\fR in url.list lets you specify the number
of times to retry, time to wait between retries, and a
timeout setting.


\fBWebsec\fR waits for a random number of seconds between
retries up to the value specified by the \fIRandomwait\fR
keyword. This is to prevent websec from being blocked by
websites that perform log analysis to find time similarities
between requests.



.SH "SEE ALSO"
/usr/share/doc/websec/README.gz.

.SH "AUTHOR"
This manual page was written by Joop Stakenborg
<pa3aba@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
